version: '3.8'

services:
  git-server:
    build:
      dockerfile: gitserver.Dockerfile
      context: .
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./repos:/var/www/git

  flaskapp:
    # Build the Flask app image from the Dockerfile in the 'flask_app' directory
    build: ./flask_app
    # Map port 5000 of the container to port 5000 on the host machine
    ports:
      - "80:80"
    # Mount the same volume as the gitserver to allow the Flask app
    # to potentially interact with the Git repository via file system access.
    volumes:
      - git_data:/git_repos
    # Ensure the Flask app starts only after the gitserver service is up
    # Environment variables are passed to the Flask container.
    # These are picked up by app.py to display the configured Git identity.
    environment:
      GIT_USER_NAME: "Ryan Low Jun Hao"
      GIT_USER_EMAIL: "23201837@sit.singaporetech.edu.sg"
    restart: unless-stopped

  sonarqube:
    # Use the official SonarQube image
    image: sonarqube:lts
    container_name: sonarqube
    environment:
      # Set SonarQube admin credentials
      SONARQUBE_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONARQUBE_JDBC_USERNAME: sonar
      SONARQUBE_JDBC_PASSWORD: sonar
      SONARQUBE_ADMIN_USERNAME: admin
      SONARQUBE_ADMIN_PASSWORD: 2301837@sit.singaporetech.edu.sg
    ports:
      - "9000:9000"  # Exposes SonarQube on port 9000
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    depends_on:
      - db
    restart: unless-stopped

  db:
    # SonarQube requires a database; using the official PostgreSQL image
    image: postgres:12
    container_name: sonarqube_db
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    volumes:
      - sonarqube_db_data:/var/lib/postgresql/data
    restart: unless-stopped

# Define named volumes for persistent data
volumes:
  git_data:  # This volume will store your Git repositories
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  sonarqube_db_data:
