name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      # Define the PostgreSQL service for SonarQube
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: sonar
          POSTGRES_PASSWORD: sonar
          POSTGRES_DB: sonar
        ports:
          - 5432:5432
        options: --health-cmd="pg_isready -U sonar" --health-timeout=5s --health-retries=3

    steps:
      # Checkout the repository to the GitHub runner
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Python environment
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      # Install dependencies
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install safety pytest selenium

      # Run dependency check using Safety
      - name: Run dependency check (Safety)
        run: |
          safety check --full-report

      # Run integration tests with pytest
      - name: Run integration tests with pytest
        run: |
          pytest --maxfail=1 --disable-warnings -q

      # Run UI tests with Selenium (assumes you have UI tests in 'tests/ui_tests')
      - name: Run UI tests with Selenium
        run: |
          python -m unittest discover -s tests/ui_tests

      # Start Flask app in the background for UI testing
      - name: Start Flask app
        run: |
          nohup flask run --host=0.0.0.0 --port=5000 &

      # Start SonarQube Analysis
      - name: Run SonarQube scan
        run: |
          docker run --rm \
            -e SONAR_HOST_URL="http://localhost:9000" \
            -e SONAR_LOGIN="admin" \
            -e SONAR_PASSWORD="2301837@sit.singaporetech.edu.sg" \
            -v $(pwd):/usr/src \
            sonarsource/sonar-scanner-cli

      # Commit changes to local Git repo inside Docker container
      - name: Commit changes to local Git repo inside Docker container
        run: |
          docker exec -T git-server git add .  # Add all changes to git
          docker exec -T git-server git commit -m "CI: Update repository with tests and changes"  # Commit
          docker exec -T git-server git push  # Push changes to the local git repo

      # Push changes to GitHub (optional step)
      - name: Push changes to GitHub
        run: |
          git push origin main
